{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: providerfinder-sm
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: providerfinder
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
