# name: CD
# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     env:
#       IMAGE_NAME: providerfinder
#     steps:
#       - uses: actions/checkout@v4
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
#           aws-region: ${{ secrets.AWS_REGION }}
#       - name: Get ECR URI
#         id: ecr
#         run: |
#           ECR_URI=$(aws ecr describe-repositories --repository-names providerfinder --region ${{ secrets.AWS_REGION }} --query "repositories[0].repositoryUri" --output text)
#           echo "ECR_URI=$ECR_URI" >> $GITHUB_OUTPUT
#       - name: Login to ECR
#         run: |
#           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.ecr.outputs.ECR_URI }}
#       - name: Build and push Docker image
#         run: |
#           IMAGE=${{ steps.ecr.outputs.ECR_URI }}:${GITHUB_SHA::7}
#           docker build -t $IMAGE -f Dockerfile .
#           docker push $IMAGE
#           echo "IMAGE=$IMAGE" >> $GITHUB_ENV
#       - name: Update kubeconfig
#         run: |
#           aws eks update-kubeconfig --name myhumana-eks --region ${{ secrets.AWS_REGION }}
#       - name: Install Helm
#         run: |
#           curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
#       - name: Deploy with Helm
#         run: |
#           helm upgrade --install providerfinder helm-chart --namespace myhumana --create-namespace --set image.repository=${{ steps.ecr.outputs.ECR_URI }} --set image.tag=${GITHUB_SHA::7}
