name: CI
on:
  pull_request:
    branches: [ main ]

jobs:
  tests_and_scans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Run tests
        run: pytest -q --maxfail=1
      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 src || true
      - name: Security scan (bandit)
        run: |
          pip install bandit
          bandit -r src || true
      - name: Terraform fmt & validate
        uses: hashicorp/setup-terraform@v2
      - name: Terraform fmt
        run: |
          cd infra/terraform
          terraform init -no-color
          terraform fmt -check || true
